# competition for Thundercleese
notifications:
  irc: "chat.freenode.net#enigma"
# disable the depth option for git allowing us to merge multiple prs simultaneously
git:
  depth: false
# don't build "feature" branches
branches:
  only:
    - "master"
    
# by default most of our jobs will be run on a linux instance
os: linux
group: travis_latest
compiler: gcc
language: cpp
dist: bionic

env:
  global:
    - OUTPUT=/tmp/test
    # this is the default config each job in the matrix overrides a subset of
    - COMPILER=gcc PLATFORM=xlib MODE=Debug GRAPHICS=OpenGL1 AUDIO=None COLLISION=None NETWORK=None WIDGETS=None EXTENSIONS="None"

before_install:
  - sudo dpkg --add-architecture i386;
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf;
  - sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="60";

install: ./CI/install_emake_deps.sh && ./CI/install_engine_deps.sh
before_script: make -j4 && make -j4 emake
script: ./emake -m Run -x MinGW32 -p Win32 -w Win32 -a DirectSound -e "DirectShow,WindowsTouch,XInput,MediaControlInterface,FileDropper,IniFileSystem" -o "/tmp/test.exe"
    
jobs:
  # don't wait for OSX
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - stage: Cross Compile
      env: COMPILER=MinGW32 PLATFORM=Win32 Widgets=Win32 AUDIO=DirectSound EXTENSIONS="DirectShow,WindowsTouch,XInput,MediaControlInterface,FileDropper,IniFileSystem" OUTPUT="/tmp/test.exe"
    - stage: Cross Compile 
      env: COMPILER=MinGW64 PLATFORM=Win32 Widgets=Win32 AUDIO=DirectSound EXTENSIONS="DirectShow,WindowsTouch,XInput,MediaControlInterface,FileDropper,IniFileSystem" OUTPUT="/tmp/test.exe"
    - stage: Cross Compile 
      env: COMPILER=gcc32
    - stage: Cross Compile 
      env: COMPILER=clang
    - stage: Cross Compile 
      env: COMPILER=clang32
    - stage: Mac OSX
      os: osx
      osx_image: xcode9.2
      env: COMPILER=clang PLATFORM=None
    - stage: Mac OSX
      os: osx
      osx_image: xcode9.2
      env: COMPILER=clang PLATFORM=None
    - stage: Test Harness
      env: TEST_HARNESS=true AUDIO=OpenAL 

